config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  scope '(:locale)', locale: /pt/ do
    root to: 'pages#home'

    resources :chatrooms, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end

    resources :professionals, only: [:create, :destroy]

    patch "users/:id/professional_status", to: "users#toggle_professional", as: :user_toggle_professional


    patch "users/:id/helper", to: "users#toggle_helper", as: :user_toggle_helper
    patch "users/:id/remove_photo", to: "users#destroy_photo", as: :user_destroy_photo
    resources :users, only: [:show] do
      resources :selected_themes, only: :create
      member do
        get :my_posts
      end
    end
    resources :selected_themes, only: :destroy
    resources :posts, only: [:index, :show, :create, :edit, :update, :destroy]

    resources :requests, only: [:create, :new] do
      resources :matching_profiles, only: [:new, :create]
    end

    resources :matching_profiles, only: [:index]
    patch "matching_profiles/:id/accepted_true", to: "matching_profiles#accepted_true", as: :accepted_true
    patch "matching_profiles/:id/accepted_false", to: "matching_profiles#accepted_false", as: :accepted_false
    resources :profile_avatars, only: [ :create, :new, :update]
  
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/matching_profile.rb
class MatchingProfile < ApplicationRecord
  belongs_to :request
  belongs_to :user
  belongs_to :professional
end

app/controllers/matching_profiles_controller.rb
class MatchingProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @matching_profiles = policy_scope(MatchingProfile.where(user: current_user))
    authorize @matching_profiles
  end

  def new
    @request = Request.find(params[:request_id])
    authorize @request
    if @request.age_min.nil? || @request.age_max.nil?
      @helpers = User.where(helper: true)
      @helpers = search_theme(@request.theme_id, @helpers)
    else
      @helpers = search_age(@request.age_min, @request.age_max)
      @helpers = search_theme(@request.theme_id, @helpers)
    end
  end

  def accepted_true
    @matching_profile = MatchingProfile.find(params[:id])
    @matching_profile.accepted = true
    authorize @matching_profile
    @matching_profile.save
    redirect_post chatrooms_path(matching_user_id: @matching_profile.request.user.id, theme_id: @matching_profile.request.theme.id), options: {authenticity_token: :auto}
  end

  def accepted_false
    @matching_profile = MatchingProfile.find(params[:id])
    @matching_profile.accepted = false
    authorize @matching_profile
    @matching_profile.save
    redirect_to matching_profiles_path
  end

  def create
    @request = Request.find(params[:request_id])
    authorize @request
    if params.has_key?(:user_helper_ids)
      params[:user_helper_ids].each do |user_helper_id|
        @matching_profile = MatchingProfile.new(request_id: @request.id, user_id: user_helper_id)
        @matching_profile.save
      end
    end
  end

  private

  def matching_profile_params
    params.require(:matching_profile).permit(:user_id)
  end

  def search_age(age_min, age_max)
    helpers = User.where(helper: true)
    year_min = DateTime.now().year - age_min.to_i
    year_max = DateTime.now().year - age_max.to_i
    helpers = helpers.where("extract(year from birth_date) <= ?", year_min)
    helpers = helpers.where("extract(year from birth_date) >= ?", year_max)
  end

  def search_theme(theme_id, helpers)
    selected_theme = SelectedTheme.where(theme_id: theme_id)
    theme_helpers = []
    selected_theme.each do |selected_theme|
      if selected_theme.user_id != current_user.id
        theme_helpers << selected_theme.user_id
      end
    end
    helpers = helpers.where(id: theme_helpers)
  end
end

app/views/matching_profiles/_modal_alert_box.thml.erb
<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center" id="exampleModalLabel">Seu pedido de ajuda foi enviado!</h5>
      </div>
      <div class="modal-body text-center">
        <h6>Enquanto aguarda as manas responderem seu pedido, veja os posts de outras manas.</h6>
        <h6>Ver relatos de pessoas que passaram por situações similares pode ser de grande ajuda! ❤️</h6>
      </div>
      <div class="modal-footer">
        <%= link_to 'Ok!', posts_path, class: "btn-request" %>
      </div>
    </div>
  </div>
</div>

app/views/matching_profiles/index.html.erb
<div class="container-page">
  <div class="container-background-match" style="background-image: url(<%= image_path 'women_hug.png' %>)">
    <% if @matching_profiles.where(accepted: nil).empty? %>
    <div class="matching-header text-center">
      <h3> <%= t('.thanks') %> <br> <%= t('.noneedforhelp')%> </h3>
    </div>
    <% else %>
    <div class="matching-header text-center">
      <h2> Manas pedindo ajuda </h2>
    </div>
    <div class="container-matching-cards-helper">
      <% @matching_profiles.each do |matching| %>
        <% if matching.accepted.nil? %>
          <div class="row">
            <div class="col-md-3 mx-1 my-2">
              <div class="matching-card-helper justify-content-around">
                <div class="avatar-matching-helper" style="background-image: url('<%= image_path("Avatars/avatar_#{matching.request.user.avatar.id}.png") %>')"></div>
                <div class="matching-info-helper">
                  <h5 class="text-center mb-2"><%= matching.request.user.nickname %></h5>
                  <h6 class="text-center mb-1"><%= DateTime.now().year - matching.request.user.birth_date.year.to_i %> anos</h6>
                  <p class="text-center mb-0"><%= matching.request.theme.title %></p>
                </div>
                <div class="icons-match text-center">
                  <%= link_to accepted_true_path(matching), method: :patch, class: "icon-help-accept", remote: true do %>
                    <i class="fas fa-check"></i>
                  <% end %>
                  <%= link_to accepted_false_path(matching), method: :patch, class: "icon-help-accept", remote: true do %>
                    <i class="fa fa-times"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/matching_profiles/new.html.erb
<div class="container-page">

  <div class="container-background" style="background-image: url(<%= image_path 'women_hug.png' %>)">
  </div>

  <div class="matching-header text-center">
    <h1> <%= t('.availablesisters') %> </h1>
    <h3> <%= t('.choosesisters') %></h3>
  </div>

  <div class="container-matching-cards text-center">
    <%= form_tag request_matching_profiles_path, method: 'POST' do %>
      <%= hidden_field_tag :request_id, @request.id %>
      <% @helpers.sort_by { rand }.each do |user_helper| %>
        <% if user_helper.professional %>
          <input type="checkbox" class="hidden" value="<%= user_helper.id %>" name="user_helper_ids[]" id="helper_user_id_<%= user_helper.id %>">
          <label for="helper_user_id_<%= user_helper.id %>">

          <div class="profile-matching-card">
            <div>
              <%= link_to t('.profile'), user_path(user_helper.id), class: "btn-perfil-purple", target: :_blank %>
            </div>

            <div class="matching-card-prof justify-content-around">
              <div class="user-infos d-flex flex-column align-items-center">
                <div class="avatar-matching" style="background-image: url('<%= image_path("Avatars/avatar_#{user_helper.avatar.id}.png") %>')"></div>
              </div>
              <div class="matching-info">
                <h4 class="text-center"><%= user_helper.nickname %></h4>
                <h6 class="text-center"><%= user_helper.professional.job_category %></h6>
                <h6 class="text-center"><%= DateTime.now().year - user_helper.birth_date.year.to_i %> <%= t('.age') %></h6>
              </div>
            </div>

          </div>

          </label>
        <% else %>
          <input type="checkbox" class="hidden" value="<%= user_helper.id %>" name="user_helper_ids[]" id="helper_user_id_<%= user_helper.id %>">
          <label for="helper_user_id_<%= user_helper.id %>">

          <div class="profile-matching-card">
            <div>
              <%= link_to t('.profile'), user_path(user_helper.id), class: "btn-perfil-purple", target: :_blank %>
            </div>

              <div class="matching-card justify-content-around">
                <div class="user-infos d-flex flex-column align-items-center">
                  <div class="avatar-matching" style="background-image: url('<%= image_path("Avatars/avatar_#{user_helper.avatar.id}.png") %>')"></div>
                </div>
                <div class="matching-info">
                  <h4 class="text-center"><%= user_helper.nickname %></h4>
                  <h6 class="text-center"><%= DateTime.now().year - user_helper.birth_date.year.to_i %> <%= t('.age') %></h6>
                </div>
              </div>
          </div>

          </label>
        <% end %>
    <% end %>

        <div class="text-center mt-5">
          <button type="button" class="transparent" data-toggle="modal" data-target="#modalExemplo">
            <%= submit_tag(t('.sendrequest'), :id=>"button-modal-request", :class=>"btn-request disabled", :name=>"submit")%>
          </button>
        </div>

      <% end %>
  </div>
</div>


<!-- Include in a partial? -->
<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center" id="exampleModalLabel"><%= t('.requestsend') %></h5>
      </div>
      <div class="modal-body text-center">
        <h6><%= t('.seeposts') %></h6>
        <h6><%= t('.canhelp') %></h6>
      </div>
      <div class="modal-footer">
        <%= link_to t('.ok'), posts_path, class: "btn-request" %>
      </div>
    </div>
  </div>
</div>