config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  scope '(:locale)', locale: /pt/ do
    root to: 'pages#home'

    resources :chatrooms, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end

    resources :professionals, only: [:create, :destroy]

    patch "users/:id/professional_status", to: "users#toggle_professional", as: :user_toggle_professional


    patch "users/:id/helper", to: "users#toggle_helper", as: :user_toggle_helper
    patch "users/:id/remove_photo", to: "users#destroy_photo", as: :user_destroy_photo
    resources :users, only: [:show] do
      resources :selected_themes, only: :create
      member do
        get :my_posts
      end
    end
    resources :selected_themes, only: :destroy
    resources :posts, only: [:index, :show, :create, :edit, :update, :destroy]

    resources :requests, only: [:create, :new] do
      resources :matching_profiles, only: [:new, :create]
    end

    resources :matching_profiles, only: [:index]
    patch "matching_profiles/:id/accepted_true", to: "matching_profiles#accepted_true", as: :accepted_true
    patch "matching_profiles/:id/accepted_false", to: "matching_profiles#accepted_false", as: :accepted_false
    resources :profile_avatars, only: [ :create, :new, :update]
  
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:nickname]
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :requests
  has_many :posts
  has_many :selected_themes
  has_many :themes, through: :selected_themes
  has_many :matching_profiles
  has_many :messages
  has_many :chatroom
  has_one_attached :photo
  has_one :professional, dependent: :destroy
  has_one :profile_avatar
  has_one :avatar, through: :profile_avatar
  validates :nickname, presence: true, uniqueness: { case_sensitive: false }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:nickname)
      where(conditions).where(["lower(nickname) = :value", { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile_avatar = ProfileAvatar.find_by(user: current_user)
    authorize current_user
    @user = User.find(params[:id])
    @selected_theme = SelectedTheme.new
    @selected_themes_existing = SelectedTheme.includes(:theme).where(user_id: current_user.id)
    @professional = Professional.new
    array_existing_theme = []
    @selected_themes_existing.each do |select_theme|
      array_existing_theme << select_theme.theme_id
    end
    @themes = Theme.where.not(id: array_existing_theme)
    @themes == nil ? Theme.all : @themes
  end

  def toggle_helper
    authorize current_user
    current_user.toggle! (:helper)
    redirect_to user_path(current_user)
  end

  def my_posts
    @posts = Post.where(user_id: current_user.id)
    authorize @posts
    @post = Post.new()
    authorize @post
  end

  # def destroy_photo
  #   authorize current_user
  #   current_user.photo.purge
  #   redirect_to edit_user_registration_path(current_user)
  # end

  # def toggle_professional
  #   authorize current_user
  #   current_user.toggle! (:professional_status)
  #   redirect_to user_path(current_user)
  # end

  private

  def params_user
    params.require(:user).permit(:selected_theme_id, :nickname, :email, :password, :helper, :professional)
  end
end

app/views/users/_modal_avatar.html.erb
 <% if current_user.avatar %>
  <div class="avatar-pencil">
    <button type="button" class="icon-update-avatar " data-toggle="modal" data-target="#exampleModal">
      <i class="fas fa-pen"></i>
    </button>
  </div>

<% else %>
  <i>Você não tem avatar por enquanto</i>
  <div class="avatar-large-black">
    <p><%= current_user.nickname %></p>
  </div>
  <button type="button" class="btn-rose" data-toggle="modal" data-target="#exampleModal">
    Escolher um avatar
  </button>
<% end %>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Escolhe seu avatar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: profile_avatar_path(@profile_avatar), method: "patch") do %>
          <fieldset class="form-group check_boxes required profile_avatar_avatar">
          <input type="hidden" name="profile_avatar[avatar_id][]" value="">
          <div class="row">
            <% Avatar.all.each do |a| %>
              <div class="col-md-4 mb-4">
                <div class="form-check">
                  <input class="hidden" type="checkbox" value=<%= a.id %> name="profile_avatar[avatar_id][]" id="profile_avatar_avatar_id_<%= a.id %>">
                  <label class="card-avatar" for="profile_avatar_avatar_id_<%= a.id %>" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('<%= image_path "Avatars/#{a.filename}.png" %>')"></label>
                </div>
              </div>
            <% end %>
          </div>
          <div class="d-flex justify-content-center">
            <%= submit_tag 'Escolhi !', class: "btn-rose", id: "btn-avatar" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_modal_profession.html.erb
<div class="d-flex justify-content-center">
  <button type="button" method="PATCH" class="btn-post-purple" id="button modal" data-toggle="modal" data-target="#Modal">
    <p style="font-size: 12px" class="m-0"><%= t('.addprofession') %></p>
  </button>
</div>
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel"><%= t('.yourprofession') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="cards-form">
          <%= simple_form_for @professional, url: professionals_path do |f| %>
            <%= f.input :job_category, collection: Professional::CATEGORIES, label: t('.profession'), input_html: { class: 'card-form' } %>
            <%= f.input :description, label: false, placeholder: t('.professiondescription'), input_html: { class: 'card-form', maxlength: 60 } %>
            <%= f.submit t('.addprofession'), class: 'btn-post' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_modal_themes.erb
<!-- Button trigger modal -->
<button type="button" id="help-button-theme" class="btn btn-primary" data-toggle="modal" data-target="#modal-theme">
  <%= t('.selectthemes') %>
</button>

<!-- Modal -->
<div class="modal fade" id="modal-theme" tabindex="-1" role="dialog" aria-labelledby="modal-theme-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-theme"><%= t('.addthemes') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= simple_form_for [current_user, @selected_theme], remote: true do |f| %>
          <div class="form-inputs">
            <fieldset class="form-group form-theme-content required">
              <% @themes.each do |theme| %>
              <div class="form-theme-choice">
                <input class="hidden-checkbox" type="checkbox" value="<%= theme.id %>" name="selected_theme[theme_id][]" id="selected_theme_theme_id_<%= theme.id %>">
                <label class="theme-choice" for="selected_theme_theme_id_<%= theme.id %>"> <%= theme.title %> </label>
              </div>
              <% end %>
            </fieldset>

      <div class="d-flex justify-content-center">
      <%= f.submit t('.helpbutton'), class: "btn-rose-outline" %>
      </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/my_posts.html.erb
<div class="container-page-myposts">
  <div class="container-background-post" style="background-image: url(<%= image_path 'womem_handsup1.png' %>)">
  <div class="container-posts-user">
    <div class="py-5 px-3">
      <% if @posts.empty? %>
        <div class="text-center mb-4">
          <h3> Você ainda não possui posts. </h3>
          <h4> Compartilhe sua história e ajude outras manas. </h4>
        </div>
        <div class="text-center">
          <button type="button" class="btn btn-primary" id="button-modal" data-toggle="modal" data-target="#exampleModal">
            Criar Publicação
          </button>
        </div>

      <% else %>

        <div class="text-center-my-post mb-4">
          <h2> Suas Publicações </h2>
          <h4> Compartilhe sua história e ajude outras manas. </h4>
        </div>
        <div class="text-center">
          <button type="button" class="btn btn-primary" id="button-modal" data-toggle="modal" data-target="#exampleModal">
            Criar Publicação
          </button>
        </div>

        <% @posts.order('created_at DESC').each do |post| %>
          <div class="posts-cards mt-4">
            <div class="d-flex justify-content-between">
              <div class="d-flex align-self-center">
                <div class="avatar-post mx-1 align-self-center" style="background-image: url('<%= image_path("Avatars/avatar_#{post.user.avatar.id}.png", crop: :fill) %>')"></div>
                <div class="post-name-avatar align-self-center"><p><%= post.user.nickname %></p></div>
              </div>
              <div class="font-theme">
                <p><%= post.theme.title %></p>
              </div>
            </div>
            <div class="post-time d-flex justify-content-between align-items-baseline">
              <% time_min = (DateTime.now().to_time - post.created_at.to_time) / 60 %>
              <% if time_min < 60  %>
                <p>Postado: <%= time_min.round %> min</p>
              <% elsif time_min > 60 && time_min < 1440 %>
                <p>Postado: <%= (time_min/60).round %> h</p>
              <% else %>
                <p><%= post.created_at.strftime(" Postado em %d-%m-%Y") %> <%= post.created_at.strftime("às %I:%M") %></p>
              <% end %>
              <div>
                <button type="button" class="transparent" style = 'text-decoration: none;' data-toggle="modal" data-target="#editModal<%= post.id %>">
                  <i class="fas fa-edit icon-edit-post"></i>
                </button>
                <%= link_to post_path(post), method: :delete, remote: true, data: { confirm: 'Tem certeza?' }, class: "icon-destroy-post",  style: 'text-decoration: none;' do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              </div>
            </div>
            <p><%= post.content %></p>
          </div>
        <% end %>

      <% end %>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Nova Publicação</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <div class="cards-form">
            <%= simple_form_for (@post), url: {controller: "posts", action: "create"} do |f| %>
              <%= f.input :content, label: false, placeholder: 'Nos conte sua história...', input_html: { class: 'card-form' } %>
              <%= f.association :theme, label: "Temática:", input_html: { class: 'card-form' } %>
              <%= f.button :submit, 'Compartilhe', class: 'btn-post' %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

<% @posts.order('created_at DESC').each do |post| %>
<!-- Modal -->
  <div class="modal fade" id="editModal<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="editModalLabel<%= post.id %>" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editModalLabel<%= post.id %>">Edite sua Publicação</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           <div class="cards-form">
              <%= simple_form_for post do |f| %>
                <%= f.input :content, label: false, input_html: { class: 'card-form' } %>
                <%= f.association :theme, label: "Temática:", input_html: { class: 'card-form' } %>
                <%= f.button :submit, 'Compartilhe', class: 'btn-post' %>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="show-user-banner" style="background-image: url('<%= image_path 'User-show-profile.png' %>')">
  <div class="container pt-5">
    <% if @user == current_user %>
      <div class="profile-info d-flex justify-content-center align-items-center">
        <div class="user">
          <div class="user-avatar">
            <div class="avatar-large" style="background-image: url('<%= image_path "Avatars/avatar_#{@user.avatar.id}", crop: :fill %>')">
              <%= render 'modal_avatar' %>
            </div>
          </div>
          <div class="edit-button-profile">
            <%= link_to edit_user_registration_path, class: "btn-sugar-edit" do %>
              <i class="fas fa-pencil-alt"></i>
              <%= t('.editprofile') %>
            <% end %>
          </div>
        </div>
        <div class="profile">
          <h2><%= current_user.nickname %></h2>
          <strong><p class="user-age"><%= DateTime.now().year - current_user.birth_date.year.to_i %> <%= t('.yearsold') %></p></strong>
          <div class="card-professional">
            <% if current_user.professional.nil? %>
              <p><%= t('.incaseprofession') %></p>
              <%= render 'modal_profession' %>
            <% else %>
              <div class="card-professional-infos">
                <div class="card-professional-job d-flex justify-content-between">
                  <%= current_user.professional.job_category %>
                  <%= link_to professional_path, method: :delete, data: {confirm: "Você quer tirar a sua profissão ?"}, class: 'btn-font-awesome mx-3 icon-update-avatar', style: "font-size: 12px" do %>
                  <i class="fas fa-times"></i>
                  <% end %>
                </div>
                <div class="card-professional-description">
                  <%= current_user.professional.description %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="help-availability d-flex align-items-center justify-content-center mt-4">
        <% if current_user.helper == false %>
          <%= link_to icon_helper("square"), user_toggle_helper_path(current_user), method: :patch, class: "icon-helper", remote: true %>
          <strong><p class="mb-0 ml-2" ><%= t('.notavailabletohelp') %></p></strong>
        <% else %>
          <%= link_to icon_helper("check-square"), user_toggle_helper_path(current_user), method: :patch, class: "icon-helper", remote: true %>
          <strong><p class="mb-0 ml-2"><%= t('.availabletohelp') %></p></strong>
        <% end %>
      </div>

      <% if current_user.helper == true %>
        <div class="form-selected-themes d-flex justify-content-center">
             <!--  <div class="title-form mb-2">
                Assuntos para ajudar
              </div> -->
              <%= render 'modal_themes' %>
        </div>
        <div class="d-flex flex-wrap justify-content-center">
          <% if current_user.themes.count != Theme.count %>
          <% end %>
          <% if current_user.selected_themes.exists? %>
            <div class="selected-themes p-4 flex-grow-2">
              <div class="d-flex flex-wrap justify-content-center" id="theme-boxes">
                <% @selected_themes_existing.each do |select_theme| %>
                  <div class="card-selected-theme d-flex align-items-center justify-content-center">
                    <p class="mb-0"><%= select_theme.theme.title %></p>
                    <%= link_to "x", selected_theme_path(select_theme), method: :delete, data: { confirm: "Certeza ?"}, class: "icon-destroy-absolute", remote: true %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>


    <% else %>
      <div class="helper-profile d-flex justify-content-center">
        <div class= "helper-profile-avatar" style="background-image: url('<%= image_path "Avatars/avatar_#{@user.avatar.id}", crop: :fill %>')"></div>
        <div class="user-show-nickname">
          <h2><%= @user.nickname %></h2>
          <p class="user-age"><%= DateTime.now().year - @user.birth_date.year.to_i %> <%= t('.yearsold') %></p>
          <div class="user">
            <% if @user.professional %>
              <div class="card-professional">
                <% if @user.professional %>
                  <div class="d-flex justify-content-between">
                    <div class="card-professional-infos">
                      <div class="card-professional-job mb-2">
                        <%= @user.professional.job_category %>
                      </div>
                      <div class="card-professional-description">
                        <%= @user.professional.description %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="d-flex align-items-center justify-content-center my-3">
        <% if @user.helper == false %>
          <div class="icon-helper-w-hover">
            <%= icon_helper("square") %>
          </div>
        <p class="mb-0 ml-2"><%= @user.nickname %> <%= t('.usernotavailable')%></p>
        <% else %>
          <div class="icon-helper-w-hover">
            <%= icon_helper("check-square") %>
          </div>
          <strong><p class="mb-0 ml-2"><%= @user.nickname %> <%= t('.useravailable') %></p></strong>
        <% end %>
      </div>

      <% if @user.selected_themes.exists? %>
        <div class="selected-themes" style="width: 100%; margin: auto">
          <div class="d-flex flex-wrap justify-content-center py-3">
            <% @user.themes.each do |theme| %>
              <div class="card-selected-theme d-flex flex-column align-items-center justify-content-center">
                <p class="m-0"><%= theme.title %></p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
</div>