config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  scope '(:locale)', locale: /pt/ do
    root to: 'pages#home'

    resources :chatrooms, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end

    resources :professionals, only: [:create, :destroy]

    patch "users/:id/professional_status", to: "users#toggle_professional", as: :user_toggle_professional


    patch "users/:id/helper", to: "users#toggle_helper", as: :user_toggle_helper
    patch "users/:id/remove_photo", to: "users#destroy_photo", as: :user_destroy_photo
    resources :users, only: [:show] do
      resources :selected_themes, only: :create
      member do
        get :my_posts
      end
    end
    resources :selected_themes, only: :destroy
    resources :posts, only: [:index, :show, :create, :edit, :update, :destroy]

    resources :requests, only: [:create, :new] do
      resources :matching_profiles, only: [:new, :create]
    end

    resources :matching_profiles, only: [:index]
    patch "matching_profiles/:id/accepted_true", to: "matching_profiles#accepted_true", as: :accepted_true
    patch "matching_profiles/:id/accepted_false", to: "matching_profiles#accepted_false", as: :accepted_false
    resources :profile_avatars, only: [ :create, :new, :update]
  
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <% if user_signed_in? %>
    <div class="page-footer-log">
              <!-- Facebook -->
          <%= link_to "https://pt-br.facebook.com/lewagon/", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
            <i class="fab fa-facebook-square" id="facebook"></i>
            <% end %>
              <!--Linkedin -->
          <%= link_to "https://www.linkedin.com/school/le-wagon/?originalSubdomain=br", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
            <i class="fab fa-linkedin" id="linkedin"></i>
            <% end %>
              <!--Instagram-->
            <%= link_to "https://www.instagram.com/lewagonbrasil/?hl=pt-br", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
              <i class="fab fa-instagram" id="instagram"></i>
            <% end %>
              <!--Twitter-->
            <%=  link_to "https://twitter.com/lewagonbrasil", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
               <i class="fab fa-twitter-square" id="twitter"></i>
            <% end %>
    </div>
    <div class="footer-copyright" id="copyright">© 2020 Copyright:
          <a href="https://www.lewagon.com/pt-BR" id="copyrighttext">#Batch354#TheBest</a>
    </div>

    <% else %>
      <div class="page-footer">
                <!-- Facebook -->
            <%= link_to "https://pt-br.facebook.com/lewagon/", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
              <i class="fab fa-facebook-square" id="facebook"></i>
              <% end %>
                <!--Linkedin -->
            <%= link_to "https://www.linkedin.com/school/le-wagon/?originalSubdomain=br", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
              <i class="fab fa-linkedin" id="linkedin"></i>
              <% end %>
                <!--Instagram-->
              <%= link_to "https://www.instagram.com/lewagonbrasil/?hl=pt-br", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
                <i class="fab fa-instagram" id="instagram"></i>
              <% end %>
                <!--Twitter-->
              <%=  link_to "https://twitter.com/lewagonbrasil", target: "_blank", style: 'text-decoration: none;', class: "social-icon" do %>
                 <i class="fab fa-twitter-square" id="twitter"></i>
              <% end %>
      </div>
      <div class="footer-copyright" id="copyright">© 2020 Copyright:
            <a href="https://www.lewagon.com/pt-BR" id="copyrighttext">#Batch354#TheBest</a>
      </div>
  <% end %>
</div>

app/views/shared/_form_homepage.html.erb
<div class="modal-sign-up">
  <button type="button" method="PATCH" class="btn-modal-rose" id="button modal" data-toggle="modal" data-target="#Modal">
    <p style="font-size: 20px" class="m-0" >Cadastre-se!</p>
  </button>
</div>
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">Seu cadastro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="cards-form">
         <%= simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nickname,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "nickname" },
                label: "Apelido" %>
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" },
                label: "Email" %>
    <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" },
                label: "Senha" %>
    <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" },
                label: "Confirmar a senha" %>
    <%= f.input :birth_date, start_year: Date.today.year - 40,
                end_year: Date.today.year - 12,
                order: [:day, :month, :year],
                required: true,
                label: "Data de nascimento" %>
  </div>

  <div class="form-actions d-flex justify-content-center">
    <%= f.button :submit, "Sign up", class: "btn-rose"%>
  </div>
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_themes.html.erb
<%= simple_form_for [current_user, @selected_theme], remote: true do |f| %>
  <div class="form-inputs">
    
    <fieldset class="form-group form-theme-content required">
      <% @themes.each do |theme| %>
        <div class="form-theme-choice">
            <input class="hidden-checkbox" type="checkbox" value="<%= theme.id %>" name="selected_theme[theme_id][]" id="selected_theme_theme_id_<%= theme.id %>">
            <label class="theme-choice" for="selected_theme_theme_id_<%= theme.id %>"> <%= theme.title %> </label>
        </div>
      <% end %>
    </fieldset>

    <div class="d-flex justify-content-center">
      <%= f.submit "Ajuda !", class: "btn-rose-outline" %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-sororitree">
  <% if user_signed_in? %>
    <p class="logo-navbar">
      <%= link_to image_tag("newlogo.png", width: 70, height: 60), posts_path, class: "link-home-page" %>
    </p>
    <div class="inbox-and-drop-down">
      <%= link_to t('.help') , new_request_path, class: "helpbutton" %>
      <%# Added a last_chat function in the helper to find the chat where the last message was sent %>
      <% if last_chat %>
        <div class="inbox-icon">
          <%= link_to chatroom_path(last_chat), class: "without-text-decoration" do %>
            <div class="matching-items-position">
              <i class='fas fa-comments' id="inbox-button"></i>
              <div class="messages-unread matching-number" data-id="<%= current_user.id %>">
                <span><%= @unread.count %></span>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <% if current_user.helper == true %>
        <%= link_to matching_profiles_path, class: "without-text-decoration" do  %>
          <div class="matching-items-position">
            <i class="fas fa-hands-helping" id="inbox-button"></i>
            <div class="matching-number">
              <span><%= @profile_matched %></span>
            </div>
          </div>
        <% end %>
    	<% end %>
      <!-- add avatar logic <-->
      <div class="nav-item dropdown">
        <%= link_to image_tag("Avatars/avatar_#{current_user.avatar.id}.png"), user_path(current_user), class: "avatar-small", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to t(".profile"),user_path(current_user), class: "dropdown-item" %>
          <%= link_to t(".posts"), my_posts_user_path(current_user), class: "dropdown-item" %>
          <%= link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
      <div>
        <%# See the URLs dfor the site's traduction in the application controller %>
        <li><%= link_to t('.french'), url_for(controller: params[:controller], action: params[:action], locale: nil) %></li>
        <li><%= link_to t('.portuguese'), url_for(controller: params[:controller], action: params[:action], locale: :pt) %></li>
      </div>
    </div>
  <% else %>
    <p class="logo-navbar ml-3">
      <%= link_to image_tag("newlogo.png", width: 80, height: 70), root_path, class: "link-home-page" %>
    </p>
    <div class="not-signed-in-navbar d-flex align-items-center">
      <p class="m-0 mr-3"> <%= t('.already_signed') %></p>
      <%= link_to t('.sign_in'), new_user_session_path, class: "btn-rose mr-2" %>
      <div>
      <%# See the URLs dfor the site's traduction in the application controller %>
        <li><%= link_to t('.french'), root_path(locale: nil) %></li>
        <li><%= link_to t('.portuguese'), root_path(locale: :pt) %></li>
      </div>
    </div>
  <% end %>
</nav>